"""
In-memory data store for MVP.

Replaces a database for the initial scaffold. All state is held in
Python dicts keyed by object ID. No persistence between restarts.

Future: replace with SQLAlchemy session + PostgreSQL.
Each dict here maps 1:1 to a future database table.
"""

from __future__ import annotations

from typing import Dict, List, Optional

from .models.task import (
    ActivityLog, AuditResult, BenchmarkComparison,
    Quote, Task, Transaction, SellerOnboardingReview,
)
from .models.user import BuyerProfile, SellerProfile, User


class InMemoryStore:
    """
    Central in-memory store. One singleton instance is shared across all routes.

    Future: replace with a SQLAlchemy Session injected via FastAPI Depends.
    """

    def __init__(self):
        # Identity
        self.users: Dict[str, User] = {}             # user_id -> User
        self.users_by_email: Dict[str, User] = {}    # email -> User (for login lookup)

        # Profiles
        self.buyers: Dict[str, BuyerProfile] = {}    # buyer_profile_id -> BuyerProfile
        self.sellers: Dict[str, SellerProfile] = {}  # seller_profile_id -> SellerProfile

        # Marketplace objects
        self.tasks: Dict[str, Task] = {}
        self.quotes: Dict[str, Quote] = {}
        self.transactions: Dict[str, Transaction] = {}
        self.audit_results: Dict[str, AuditResult] = {}
        self.benchmark_comparisons: Dict[str, BenchmarkComparison] = {}
        self.activity_logs: List[ActivityLog] = []  # Ordered list; most recent last

        # Seller onboarding reviews — one per seller registration
        self.seller_onboarding_reviews: Dict[str, SellerOnboardingReview] = {}

    # ------------------------------------------------------------------
    # User helpers
    # ------------------------------------------------------------------

    def add_user(self, user: User) -> User:
        self.users[user.id] = user
        self.users_by_email[user.email] = user
        return user

    def get_user_by_email(self, email: str) -> Optional[User]:
        return self.users_by_email.get(email)

    def get_user(self, user_id: str) -> Optional[User]:
        return self.users.get(user_id)

    # ------------------------------------------------------------------
    # Scoped query helpers — enforce role-based data visibility
    # ------------------------------------------------------------------

    def get_tasks_for_buyer(self, buyer_profile_id: str) -> List[Task]:
        """Buyer sees only their own tasks."""
        return [t for t in self.tasks.values() if t.buyer_id == buyer_profile_id]

    def get_tasks_for_seller(self, seller_profile_id: str) -> List[Task]:
        """Seller sees only tasks assigned to them."""
        return [t for t in self.tasks.values() if t.selected_seller_id == seller_profile_id]

    def get_quotes_for_buyer(self, buyer_profile_id: str) -> List[Quote]:
        """Return quotes for tasks owned by this buyer."""
        buyer_task_ids = {t.id for t in self.get_tasks_for_buyer(buyer_profile_id)}
        return [q for q in self.quotes.values() if q.task_id in buyer_task_ids]

    def get_quotes_for_task(self, task_id: str) -> List[Quote]:
        """Return all quotes for a specific task, ordered by match_score descending."""
        quotes = [q for q in self.quotes.values() if q.task_id == task_id]
        return sorted(quotes, key=lambda q: q.match_score, reverse=True)

    def get_quotes_for_seller(self, seller_profile_id: str) -> List[Quote]:
        """Return quotes generated by this seller."""
        return [q for q in self.quotes.values() if q.seller_id == seller_profile_id]

    def get_audit_results_for_seller(self, seller_profile_id: str) -> List[AuditResult]:
        """Return audit results for tasks this seller completed."""
        seller_task_ids = {t.id for t in self.get_tasks_for_seller(seller_profile_id)}
        return [a for a in self.audit_results.values() if a.task_id in seller_task_ids]

    def get_tasks_pending_audit(self) -> List[Task]:
        """Return completed tasks that have no audit result yet."""
        from .models.enums import TaskStatus
        return [
            t for t in self.tasks.values()
            if str(t.status) == TaskStatus.COMPLETED
            and not t.audit_result_id
        ]

    def get_audit_queue_summary(self) -> dict:
        """
        Summary of the audit workload for the auditor console.
        Returns counts by audit_status.
        """
        from .models.enums import AuditStatus
        tasks = list(self.tasks.values())
        return {
            "completed_unaudited":  sum(1 for t in tasks if not t.audit_result_id and str(t.status) == "completed"),
            "audit_passed":         sum(1 for t in tasks if str(t.audit_status) == AuditStatus.PASSED),
            "audit_failed":         sum(1 for t in tasks if str(t.audit_status) == AuditStatus.FAILED),
            "audit_overridden":     sum(1 for t in tasks if str(t.audit_status) == AuditStatus.OVERRIDDEN),
            "seller_reviews_queued": sum(
                1 for r in self.seller_onboarding_reviews.values()
                if r.review_status in ("queued", "needs_review")
            ),
            "seller_reviews_approved": sum(
                1 for r in self.seller_onboarding_reviews.values()
                if r.review_status == "approved"
            ),
        }

    def get_benchmark_comparisons_summary(self) -> dict:
        """
        Aggregate benchmark statistics across all comparisons.
        Used by the admin console to show the overall specialist vs. generalist picture.
        """
        comparisons = list(self.benchmark_comparisons.values())
        if not comparisons:
            return {
                "total_comparisons": 0,
                "seller_wins": 0,
                "generalist_wins": 0,
                "ties": 0,
                "seller_win_rate": None,
                "avg_delta": None,
                "avg_specialist_score": None,
                "avg_generalist_score": None,
                "by_category": {},
                "by_recommendation": {},
            }

        seller_wins = sum(1 for c in comparisons if c.winner == "seller")
        gen_wins = sum(1 for c in comparisons if c.winner == "generalist")
        ties = sum(1 for c in comparisons if c.winner == "tie")
        n = len(comparisons)

        by_category: dict = {}
        for c in comparisons:
            cat = c.task_category or "unknown"
            if cat not in by_category:
                by_category[cat] = {"seller_wins": 0, "generalist_wins": 0, "ties": 0, "count": 0}
            by_category[cat]["count"] += 1
            if c.winner == "seller":
                by_category[cat]["seller_wins"] += 1
            elif c.winner == "generalist":
                by_category[cat]["generalist_wins"] += 1
            else:
                by_category[cat]["ties"] += 1

        by_rec: dict = {}
        for c in comparisons:
            r = c.recommendation
            by_rec[r] = by_rec.get(r, 0) + 1

        return {
            "total_comparisons": n,
            "seller_wins": seller_wins,
            "generalist_wins": gen_wins,
            "ties": ties,
            "seller_win_rate": round(seller_wins / n, 3) if n else None,
            "avg_delta": round(sum(c.delta for c in comparisons) / n, 3),
            "avg_specialist_score": round(sum(c.seller_score for c in comparisons) / n, 3),
            "avg_generalist_score": round(sum(c.generalist_score for c in comparisons) / n, 3),
            "by_category": by_category,
            "by_recommendation": by_rec,
        }

    def get_onboarding_review_for_seller(
        self, seller_profile_id: str
    ) -> Optional[SellerOnboardingReview]:
        """Return the onboarding review record for this seller (one per seller)."""
        return next(
            (r for r in self.seller_onboarding_reviews.values()
             if r.seller_profile_id == seller_profile_id),
            None,
        )

    def get_sellers_by_review_status(self, status: str) -> List[SellerProfile]:
        """Return seller profiles whose onboarding review matches the given status."""
        reviewed_ids = {
            r.seller_profile_id
            for r in self.seller_onboarding_reviews.values()
            if r.review_status == status
        }
        return [s for s in self.sellers.values() if s.id in reviewed_ids]

    def get_logs_for_buyer(self, buyer_user_id: str, limit: int = 100) -> List[ActivityLog]:
        """Buyer sees log entries where they are the actor or the entity is their task."""
        logs = [
            l for l in self.activity_logs
            if l.actor_id == buyer_user_id
            or (l.entity_type == "task" and l.entity_id in {
                t.id for t in self.tasks.values()
                if t.buyer_id in {
                    bp.id for bp in self.buyers.values()
                    if bp.user_id == buyer_user_id
                }
            })
        ]
        return logs[-limit:]

    def get_logs_for_seller(self, seller_user_id: str, limit: int = 100) -> List[ActivityLog]:
        """Seller sees log entries where they are the actor."""
        logs = [l for l in self.activity_logs if l.actor_id == seller_user_id]
        return logs[-limit:]

    # ------------------------------------------------------------------
    # Activity log helpers
    # ------------------------------------------------------------------

    def log(
        self,
        event_type: str,
        entity_type: str,
        entity_id: str,
        message: str,
        actor_id: str | None = None,
        actor_role: str | None = None,
        metadata: dict | None = None,
    ) -> ActivityLog:
        entry = ActivityLog(
            event_type=event_type,
            actor_id=actor_id,
            actor_role=actor_role,
            entity_type=entity_type,
            entity_id=entity_id,
            message=message,
            metadata=metadata or {},
        )
        self.activity_logs.append(entry)
        return entry

    def get_logs(self, limit: int = 100, entity_id: str | None = None) -> List[ActivityLog]:
        """Return recent activity logs, optionally filtered by entity_id. Admin view."""
        logs = self.activity_logs
        if entity_id:
            logs = [l for l in logs if l.entity_id == entity_id]
        return logs[-limit:]

    def get_marketplace_analytics(self, lookback_hours: int = 24) -> dict:
        """
        Compute a full marketplace analytics snapshot and return as a dict.

        Delegates all calculation logic to analytics/marketplace.py so the
        store stays a thin data layer.

        Future: cache the result for N seconds to avoid recomputing on every
        admin page poll.
        """
        from .analytics.marketplace import compute_marketplace_snapshot
        snapshot = compute_marketplace_snapshot(self, lookback_hours=lookback_hours)
        return snapshot.to_dict()


# Singleton store instance — imported by routes
store = InMemoryStore()
