"""
Task and transaction domain models.

Task is the central object in AMPS. Every service request — regardless of
category — uses this single schema. This standardization is intentional:
it allows the routing layer, auditor, and benchmark comparison to work
uniformly across all service types.

Future: migrate to SQLAlchemy ORM models with Alembic migrations.
"""

from __future__ import annotations

import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, Field

from .enums import TaskCategory, TaskStatus, AuditStatus, OutputType


# ---------------------------------------------------------------------------
# Task (core marketplace object)
# ---------------------------------------------------------------------------

class Task(BaseModel):
    """
    The universal service request schema used across all categories.

    Design note: all four service categories (financial_research,
    legal_analysis, market_intelligence, strategy_business_research) share
    this exact schema. Category-specific behavior lives in the agent layer,
    not in the data model.

    Future fields to consider: deadline, priority_level, attachments[],
    buyer_feedback, escrow_amount.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))

    # Identity
    buyer_id: str                             # FK -> BuyerProfile.id
    title: str
    description: str                          # The buyer's natural-language prompt / brief
    category: TaskCategory
    requested_output_type: OutputType

    # Lifecycle
    status: TaskStatus = TaskStatus.PENDING
    created_at: datetime = Field(default_factory=datetime.utcnow)
    updated_at: datetime = Field(default_factory=datetime.utcnow)
    completed_at: Optional[datetime] = None

    # Routing — marketplace matching results
    # shortlisted_seller_ids: ordered list from matching engine (best first)
    shortlisted_seller_ids: List[str] = Field(default_factory=list)
    selected_seller_id: Optional[str] = None   # FK -> SellerProfile.id; set on seller selection
    selected_quote_id: Optional[str] = None    # FK -> Quote.id; set when buyer accepts a quote
    quote_ids: List[str] = Field(default_factory=list)  # All quotes generated for this task
    # marketplace_run_at: timestamp when matching was last triggered
    marketplace_run_at: Optional[datetime] = None

    # Context
    context_url: Optional[str] = None         # Optional reference URL for the task
    additional_context: Optional[Dict[str, Any]] = {}  # Freeform metadata

    # Results
    seller_result: Optional[Dict[str, Any]] = None    # Specialist seller's output
    generalist_result: Optional[Dict[str, Any]] = None  # Baseline generalist's output

    # Benchmarking
    generalist_comparison_enabled: bool = True  # Whether generalist runs in parallel
    benchmark_comparison_id: Optional[str] = None  # FK -> BenchmarkComparison.id

    # Audit
    audit_status: AuditStatus = AuditStatus.NOT_STARTED
    audit_result_id: Optional[str] = None     # FK -> AuditResult.id

    class Config:
        use_enum_values = True


# ---------------------------------------------------------------------------
# Quote
# ---------------------------------------------------------------------------

class Quote(BaseModel):
    """
    A seller's price and ETA estimate for a specific task.

    For FIXED pricing sellers, quotes are auto-generated from base_price.
    For QUOTED pricing sellers, quotes are generated by the seller agent.

    Future: add expiry_at, negotiation_rounds, counter_quote support.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str                              # FK -> Task.id
    seller_id: str                            # FK -> SellerProfile.id
    proposed_price: float                     # USD
    estimated_minutes: int
    confidence_score: float                   # Seller's self-reported confidence for this task
    notes: Optional[str] = None              # Seller's optional explanation / breakdown

    # Marketplace matching fields — added by marketplace/quoting.py
    match_score: float = 0.0                  # 0.0–1.0 composite match score from matching engine
    fit_explanation: Optional[str] = None     # Human-readable explanation of why this seller was matched
    # score_breakdown: per-dimension scores used to compute match_score
    # Keys: category_relevance, benchmark, reputation, price, confidence, capacity
    score_breakdown: Dict[str, float] = Field(default_factory=dict)
    seller_display_name: Optional[str] = None  # Denormalised for easy display without a join

    accepted: bool = False
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Transaction
# ---------------------------------------------------------------------------

class Transaction(BaseModel):
    """
    Records the financial settlement for a completed task.

    For MVP, this is a record-only model (no real payment processing).
    Future: integrate Stripe or crypto escrow; add refund_id, dispute_id.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str                              # FK -> Task.id
    buyer_id: str                             # FK -> BuyerProfile.id
    seller_id: str                            # FK -> SellerProfile.id
    quote_id: str                             # FK -> Quote.id
    amount: float                             # USD; final settled amount
    status: str = "settled"                   # Future: "pending", "refunded", "disputed"
    settled_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Audit Result
# ---------------------------------------------------------------------------

class AuditResult(BaseModel):
    """
    The auditor agent's evaluation of a completed task's output.

    Dimension scores (each 0.0–1.0):
      quality      — output depth, reasoning quality, task alignment
      relevance    — how well the output addresses the specific task description
      completeness — presence of all expected output elements for this category
      genericity   — inverted: 1.0 = highly specific, 0.0 = entirely generic

    composite_score: weighted average of all dimensions (used for pass/fail).
    quality_score:   kept for backwards compatibility; equals composite_score.

    admin_override: True if admin manually reversed the auditor's decision.
    overridden_at:  timestamp of override (None if no override).

    scoring_method: "mock_heuristic" for MVP; "llm_judge" when real LLM wired.

    Future: add buyer_feedback_score once buyer rating flow is implemented.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str                                    # FK -> Task.id
    auditor_id: str                                 # FK -> AuditorProfile.id

    # --- Composite score (primary) ---
    composite_score: float = 0.0                    # Weighted average of dimension scores
    quality_score: float = 0.0                      # Alias for composite_score (backwards compat)
    passed: bool = False                            # composite_score >= QUALITY_THRESHOLD

    # --- Per-dimension scores ---
    dimension_scores: Dict[str, float] = Field(default_factory=dict)
    # Expected keys: "quality", "relevance", "completeness", "genericity"

    # --- Flags and narrative ---
    reasoning: str = ""                             # Auditor's explanation
    flags: List[str] = Field(default_factory=list)  # Issues: ["too_generic", "missing_risk_analysis"]
    recommendations: List[str] = Field(default_factory=list)  # Improvement suggestions

    # --- Benchmark context (populated if generalist comparison exists) ---
    has_benchmark: bool = False
    benchmark_comparison_id: Optional[str] = None  # FK -> BenchmarkComparison.id
    benchmark_winner: Optional[str] = None         # "seller" | "generalist" | "tie"
    benchmark_delta: Optional[float] = None        # seller_score - generalist_score

    # --- Admin override ---
    admin_override: bool = False
    admin_override_reason: Optional[str] = None
    overridden_at: Optional[datetime] = None
    overridden_by_user_id: Optional[str] = None

    # --- Metadata ---
    scoring_method: str = "mock_heuristic"         # "mock_heuristic" | "llm_judge"
    audited_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Benchmark Comparison
# ---------------------------------------------------------------------------

class BenchmarkComparison(BaseModel):
    """
    Full side-by-side comparison record: specialist seller vs. generalist baseline.

    This record is the core evidence for the thesis that specialized sellers
    outperform general-purpose agents on structured professional tasks.

    Created after both seller_result and generalist_result are present on a Task.
    Stored in store.benchmark_comparisons and linked from Task.benchmark_comparison_id.

    Scoring dimensions (each 0.0–1.0, scored independently):
      - quality:       output quality vs. task brief (depth, accuracy, relevance)
      - structure:     output format match to requested_output_type
      - specificity:   domain-specific detail vs. generic content
      - completeness:  all required elements present

    recommendation: human-readable conclusion for the admin/buyer console.
      "use_specialist"   — specialist clearly better; specialization adds value
      "use_generalist"   — generalist competitive; consider cost savings
      "tie"              — no significant difference; either is acceptable
      "insufficient_data" — scores too close to draw conclusion

    Future: feed winner/delta into seller.reputation_score and
    generalist.benchmark_score automatically after each comparison.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    task_id: str                                    # FK -> Task.id
    task_category: Optional[str] = None            # Denormalised for filtering
    seller_id: str                                  # FK -> SellerProfile.id
    seller_display_name: Optional[str] = None       # Denormalised
    generalist_id: str                              # FK -> GeneralistProfile.id
    generalist_model: Optional[str] = None          # Denormalised model identifier

    # ----- Quality scores (0.0–1.0) -----
    seller_score: float                             # Composite quality score
    generalist_score: float                         # Composite quality score

    # Per-dimension breakdown (placeholder values for MVP; replace with LLM judge)
    seller_dimension_scores: Dict[str, float] = Field(default_factory=dict)
    generalist_dimension_scores: Dict[str, float] = Field(default_factory=dict)

    # ----- Cost comparison -----
    specialist_cost: float = 0.0                    # USD — from accepted Quote.proposed_price
    generalist_cost: float = 0.0                    # USD — from GeneralistProfile.cost_per_task

    # ----- ETA comparison -----
    specialist_eta_minutes: int = 0                 # From SellerProfile.estimated_minutes
    generalist_eta_minutes: int = 0                 # From GeneralistProfile.estimated_minutes

    # ----- Outcome -----
    winner: str = "tie"                             # "seller" | "generalist" | "tie"
    delta: float = 0.0                              # seller_score - generalist_score
    recommendation: str = "insufficient_data"       # See docstring
    summary: Optional[str] = None                  # Human-readable explanation

    # ----- Scoring method flag -----
    # scoring_method: "mock_heuristic" for MVP; "llm_judge" when real LLM wired
    scoring_method: str = "mock_heuristic"
    mock: bool = True                               # Cleared when real scoring is wired

    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Activity Log / Event Log
# ---------------------------------------------------------------------------

class ActivityLog(BaseModel):
    """
    Immutable event log entry. Every significant state change or agent action
    emits an ActivityLog entry.

    This is the data source for the observability console in the frontend.

    actor_id: the user or agent that triggered the event (nullable for system events).
    entity_type / entity_id: the object the event relates to (e.g. Task, Quote).

    Future: stream these to a message bus (Kafka, Redis Streams) for real-time
    fanout. For MVP, these are stored in-memory and polled by the frontend.
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    event_type: str          # e.g. "task.created", "seller.assigned", "audit.passed"
    actor_id: Optional[str] = None            # FK -> User.id; null = system event
    actor_role: Optional[str] = None          # UserRole value for display
    entity_type: str         # "task" | "quote" | "transaction" | "audit_result" | "user"
    entity_id: str           # ID of the affected object
    message: str             # Human-readable description for the console
    metadata: Optional[Dict[str, Any]] = {}   # Arbitrary structured context
    created_at: datetime = Field(default_factory=datetime.utcnow)  # Timestamp for log feed ordering


# ---------------------------------------------------------------------------
# Seller Onboarding Review
# ---------------------------------------------------------------------------

class SellerOnboardingReview(BaseModel):
    """
    Auditor readiness record created automatically when a seller registers.

    Tracks the outcome of the auditor's evaluation of a seller's onboarding
    submission — separate from task-level AuditResult records.

    review_status mirrors the seller's approval_status progression:
      queued → in_review → approved | rejected | needs_more_info

    dimension_scores: optional per-dimension breakdown for richer feedback.
    Keys are: "completeness", "expertise_credibility", "pricing_clarity",
              "category_fit", "capacity_realism"

    Future: store multiple review cycles (resubmission after rejection).
    """
    id: str = Field(default_factory=lambda: str(uuid.uuid4()))
    seller_profile_id: str                     # FK -> SellerProfile.id
    auditor_id: Optional[str] = None           # FK -> AuditorProfile.id; None = system review
    review_status: str = "queued"              # queued | in_review | approved | rejected | needs_more_info
    overall_score: Optional[float] = None      # 0.0–1.0 overall quality score
    dimension_scores: Dict[str, float] = Field(default_factory=dict)
    passed: Optional[bool] = None              # True = recommend APPROVED, False = recommend REJECTED
    issues: List[str] = Field(default_factory=list)   # Specific problems found
    recommendations: List[str] = Field(default_factory=list)  # Suggested improvements
    reasoning: Optional[str] = None            # Auditor's overall explanation
    # --- Admin override ---
    admin_override: bool = False
    admin_override_reason: Optional[str] = None
    overridden_at: Optional[datetime] = None
    overridden_by_user_id: Optional[str] = None

    # --- Auditor annotation (set when human auditor adds comments) ---
    auditor_comment: Optional[str] = None          # Free-text human notes from auditor

    created_at: datetime = Field(default_factory=datetime.utcnow)
    reviewed_at: Optional[datetime] = None         # Set when human auditor completes review
    # NOTE: no duplicate created_at — was a bug in prior version
